# Site settings
title: Rosie Leagas, Independent
subtitle: for Strathbogie, Huntly and Howe of Alford
email: rosieleagas@gmail.com
url: rosieleagas.co.uk
description: "Independent for Huntly, Strathbogie and the Howe of Alford"
keywords: "aberdeenshire council"
skills: "Farming -- Hospitality -- Zoology"
meta_author: Leagas Rosie

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Rosie Leagas
  location: Location
  social: LinkedIn
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/rosie-wilson-leagas-5997683a

# Postal address (add as many lines as necessary)
address:
  - line: West Wing Flat
  - line: Leith Hall
  - line: Kennethmont

# Credits content
credits: 'Website by Fergus Fettes. Promoted by Rosie Leagas'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
